AerynOS/os-tools

- Cargo.lock
- Cargo.toml
- moss/Cargo.toml
- moss/src/config.rs
- moss/src/lib.rs
Simple module to enumerate admin / vendor paths for a certain "domain" and return a merged config
> Add config loading

- .github/dependabot.yml
- Cargo.toml
Analogue to https://github.com/serpent-os/usysconf-rs/pull/3
> Enable automatic dependency updates

- moss/src/cli/install.rs
- moss/src/cli/remove.rs
- moss/src/cli/state.rs
- moss/src/client/mod.rs
- moss/src/client/prune.rs
- moss/src/db/state/migrations/20230912172712_init.sql
- moss/src/db/state/mod.rs
- moss/src/package/mod.rs
- moss/src/registry/plugin/active.rs
- moss/src/state.rs
Breaking change, make sure to delete any previous `-D` root
> Mark selections as explicit

- crates/boulder/src/builder.rs
- crates/boulder/src/cli/chroot.rs
- crates/boulder/src/container.rs
- crates/boulder/src/job/step.rs
- crates/boulder/src/lib.rs
- crates/stone_recipe/src/script.rs
> Add actions & definitions into chroot environment

- crates/moss/src/client/install.rs
- crates/moss/src/package/mod.rs
> Don't allow updates via install

- Cargo.toml
- crates/boulder/src/cli.rs
- crates/moss/build.rs
- crates/moss/src/cli/version.rs
- crates/moss/src/environment.rs
> Add git hash to moss & boulder version

- Cargo.lock
- crates/boulder/Cargo.toml
- crates/boulder/src/cli.rs
- crates/boulder/src/cli/recipe.rs
- crates/yaml/Cargo.toml
- crates/yaml/src/lib.rs
- crates/yaml/src/updater.rs
> Add boulder update

- crates/moss/src/cli/inspect.rs
Now that we have conflicts, detecting dependencies/provides solely based on the meta kind is not enough. We should use the meta tag to detect them.
Also it seems like the previous implementation got providers and dependencies in reverse? This also fixes that. Tested on the `boulder` stone to make sure that providers/dependencies/conflicts are correctly detected.
> moss/inspect: detect dependencies/provides based on meta tag

- crates/moss/src/db/layout/mod.rs
- crates/moss/src/db/meta/mod.rs
- crates/moss/src/db/state/mod.rs
Ensure we have exclusive access to prevent issues since we're async up the wazoo
We may be able to use `SQLITE_OPEN_FULLMUTEX` https://www.sqlite.org/threadsafe.html instead, but I don't have a good reproducible way to test either way.
> Wrap databases in Mutex

- crates/moss/src/cli/info.rs
- crates/moss/src/client/mod.rs
- crates/vfs/src/lib.rs
Example of difference between regular file vs symlink
> Print installed files for moss info -f

- crates/moss/src/cli/list.rs
Nice when dumping packages when migrating to a new install :)
> Add --explicit flag for list installed

- Cargo.lock
- boulder/Cargo.toml
- boulder/src/architecture.rs
- boulder/src/build.rs
- boulder/src/cli/build.rs
- boulder/src/lib.rs
- boulder/src/package.rs
- boulder/src/package/emit.rs
- boulder/src/timing.rs
Resolves https://github.com/serpent-os/moss/issues/152
> Add timings to boulder output

- boulder/data/profile.d/default-x86_64.yaml
- boulder/src/cli/profile.rs
- boulder/src/profile.rs
Resolves https://github.com/serpent-os/moss/issues/151
> Rename collections -> repositories

- moss/src/client/mod.rs
- moss/src/db/layout/mod.rs
- moss/src/db/meta/mod.rs
- moss/src/package/mod.rs
- moss/src/registry/mod.rs
- moss/src/registry/plugin/active.rs
- moss/src/registry/plugin/mod.rs
- moss/src/registry/plugin/repository.rs
- moss/src/registry/transaction.rs
> Optimizations :D

- Cargo.toml
- boulder/src/package/emit.rs
- crates/stone/src/lib.rs
- crates/stone/src/write.rs
- crates/stone/src/write/zstd.rs
> boulder/stone: Enable multithreaded compression

- boulder/data/macros/actions/python.yml
Compiles .pyc bytecode files from .py files and renames python to python_setup.
> boulder/data/macros: Provide python_compile & rename python macros

- boulder/src/build.rs
- boulder/src/build/root.rs
- boulder/src/cli/build.rs
- boulder/src/package.rs
- boulder/src/timing.rs
- moss/src/cli/install.rs
- moss/src/client/install.rs
- moss/src/client/mod.rs
> boulder: Moar timings

- boulder/src/package.rs
- boulder/src/package/emit.rs
- boulder/src/package/emit/manifest.rs
- boulder/src/package/emit/manifest/binary.rs
- boulder/src/package/emit/manifest/json.rs
> Set manifest.bin build_release to zero

- moss/src/cli/state.rs
- moss/src/client/mod.rs
- moss/src/client/verify.rs
- moss/src/db/state/mod.rs
- moss/src/state.rs
Resolves https://github.com/serpent-os/moss/issues/126
> moss: Add verify command

- boulder/src/cli/recipe.rs
Increments the release of a recipe by one or optionally set release to any value.
> boulder: Implement recipe bump support

- boulder/src/cli/recipe.rs
https://github.com/serpent-os/moss/assets/10239377/2808a2da-035a-4ce8-8f3f-6071d056c13b
> boulder: update: Add progress & fix version flag conflict

- boulder/data/macros/actions/pgo.yaml
- boulder/data/macros/arch/base.yaml
- boulder/src/build/job/phase.rs
Allows the packager to perform stage specific actions in a pgo build
> boulder: Export current PGO stage into environment

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
I'm not completely certain w.r.t. caches of the nightly thing, but I guess it will be pretty obvious with the next nightly (currently the times are pretty stable at slightly above 5min).
> Moar CI updates

- moss/src/cli/sync.rs
- moss/src/registry/transaction.rs
Transaction resolution was borked in `sync` due to the fact we were explicitly adding transitive packages to the transaction.
This is incorrect since transitive packages should only get added to a transaction via provider resolution from a dependent explicit package. There are two issues from doing this:
- The explicitly added transitive might be a different version than what's resolved from the dependent explicit during provider resolution. Both versions would end up in the final TX.
- Transitives of the explicitly added transitive might be orphaned if the newer explicitly added transitive version no longer has that dependency. Then that orphaned transitive got added because we added all original transitives from the old state.
Even if we solve the above by removing orphaned packages …
> moss: Fix sync transaction & use pinned providers

- moss/src/cli/sync.rs
We shouldn't error out if an installed package isn't available in a remote repo. Instead, we just keep
the package as is.
Resolves #307
> moss: Allow sync on installed pkg missing from repos

- moss/src/client/cache.rs
- moss/src/client/prune.rs
> moss: Download packages to partial file then rename

- .gitignore
- boulder/src/package/emit/manifest/json.rs
- moss/src/client/mod.rs
Best reviewed ignoring whitespace changes.
> Fix new compiler, clippy warnings

- boulder/src/build/job/phase.rs
- boulder/src/build/root.rs
- boulder/src/package.rs
> boulder: Inherit root build if profile is missing phase

- boulder/src/package/analysis/handler.rs
Add a versioned in addition to the generic provider. This will help with autodep breaking in the case of automatic dependencies.
In the future if we provide more than one python interpreter we will need to drop the generic provider for the "non-main" python candidate.
> boulder: Add versioned python providers

- boulder/src/cli/profile.rs
- moss/src/cli/mod.rs
- moss/src/cli/repo.rs
- moss/src/registry/plugin/repository.rs
- moss/src/repository/manager.rs
- moss/src/repository/mod.rs
> moss: Add ability to disable repositories

- crates/stone/src/payload/index.rs
- crates/tui/src/pretty.rs
- moss/src/client/install.rs
- moss/src/package/render.rs
… if it's larger than 1.
Also fix a clippy lint.
> Add build_release to moss sync version table

- boulder/src/util.rs
- crates/container/src/lib.rs
- moss/src/cli/extract.rs
- moss/src/client/cache.rs
- moss/src/client/mod.rs
Use fs::function style consistently.
> Stop importing fs_err's free functions into scope

- moss/src/client/verify.rs
Issue packages can come from states that are not active and it's possible those packages comes from repos that are no longer available. Those packages still exist in our layout / install dbs until pruned from all states, but since we were querying via Registry API, it only considers packages from available repos or the active state.
Resolves #392
> moss: verify: query installdb directly

- moss/src/client/mod.rs
> moss: cli: Add blit stats

- boulder/data/macros/arch/base.yaml
> boulder: Add .gir files to devel

- boulder/Cargo.toml
- boulder/src/package/analysis/handler/elf.rs
For https://github.com/AerynOS/os-tools/issues/231
> boulder: Emul32 migration part 3

- Cargo.lock
- Cargo.toml
- moss/Cargo.toml
- moss/src/cli/mod.rs
- moss/src/cli/sync.rs
- moss/src/registry/transaction.rs
> Add debug logging for sync

- crates/dag/src/lib.rs
- crates/stone_recipe/src/script.rs
- crates/stone_recipe/src/tuning.rs
- crates/triggers/src/lib.rs
- moss/src/cli/mod.rs
- moss/src/cli/remove.rs
- moss/src/client/prune.rs
- moss/src/registry/transaction.rs
See individual commit messages :)
> Some refactorings, again

- Cargo.lock
- Cargo.toml
- crates/stone/benches/read.rs
Get rid of duplicate versions of `nix`, `rustix` _and_ `linux-raw-sys` 🙌🏼
> Upgrade some dependencies

- moss/src/cli/index.rs
> moss: Add path as context to index::Error::StoneWrite

- boulder/src/cli.rs
- moss/src/cli/mod.rs
> boulder/moss: add version flag

- .github/workflows/release.yaml
Follow-up to changing the nightly workflow into a (tagged) release
workflow.
> ci: Clean up release workflow

- boulder/src/package/analysis/handler.rs
- boulder/src/package/analysis/handler/python.rs
Part of aerynos/os-tools#496
Do not merge until we have the repo rebuild complete
> boulder: Normalize Python providers/dependencies properly

- boulder/src/build/git.rs
fix for this bug: https://gist.github.com/ermo/4f4f5eddb93780b9c14d072abd494eec
> do not try to resolve git upstream hashes if they are already provided

- moss/src/client/verify.rs
Alternative to #421.
Resolves #390.
This avoids leaking anything about the execution order into the output. It could however be quite hard to extend for anybody not strongly familiar with advanced iterator combinators (and rayon adds a little bit of complexity of its own).
I expect this to be no slower than #421, potentially faster. I have not verified this code in any way beyond making sure it compiles. I would love to find a less complex-looking solution to this, and maybe there is (now that I'm thinking about it, I vaguely remember seeing a crate that helps with fallible parallel list building using rayon).
> moss: Parallel state verify with rayon iterators
