AerynOS/os-tools

moss/src/cli/mod.rs

`cargo run -p moss -- -h`:
```
Next generation package manager
Usage: moss [OPTIONS] [COMMAND]
Commands:
extract  Extract a `.stone` content to disk
info     Query packages
inspect  Examine raw stone files
install  Install packages
list     List packages
remove   Remove packages
version  Display version and exit
help     Print this message or the help of the given subcommand(s)
Options:
-v, --version           
-D, --directory <root>  Root directory [default: /]
-y, --yes-all           Assume yes for all questions
-h, --help              Print help
```
`cargo run -p moss -- install -h`:
```
Install packages
Usage: moss install [OPTIONS]
Options:
-D, --directory <root>  Root directory [default: /]
-y, --yes-all           Assume yes for all questions
-h, --help              Print help (see …
```

moss/cli: add -D and -y global arguments

---

Cargo.lock
Cargo.toml
moss/Cargo.toml
moss/src/cli/extract.rs

An example of doing `copy` in parallel from the stone content file to the store.
It appears to be around 20% faster based on some benchmarking

Extract content in parallel

---

moss/src/cli/install.rs
moss/src/package/render.rs
moss/src/registry/mod.rs
moss/src/registry/plugin/mod.rs

Plugins can have priority collision so we can't use btreeset. Ordering is now guaranteed by sorting during query iteration.

Use vec instead of btreeset

---

moss/src/cli/install.rs
moss/src/db/layout/mod.rs

Remove layout entries related to package id before batch adding to prevent dupes between installs

Prevent layout dupes per package

---

.github/workflows/nightly.yaml

Creates releases with a binary of latest moss:
https://github.com/serpent-os/moss-rs/releases/tag/nightly-20231121-164115
Also only keeps the last 5 versions.

Add workflow for nightly builds

---

.github/workflows/ci.yaml
.github/workflows/nightly.yaml

[Makes it run with Nodejs 20 instead of 16](https://github.com/actions/checkout/blob/v4/CHANGELOG.md#v400)

Update checkout action to v4

---

crates/config/src/lib.rs
crates/moss/src/cli/repo.rs
crates/moss/src/repository/manager.rs
crates/moss/src/repository/mod.rs

Add `repo remove` CLI option
Note that since our config format allows any config file to hold a map of entries, this command only succeeds if the config for the repo is in it's own config file w/ matching repo name. Otherwise it prompts user to manually delete the config.

Add repo remove command

---

crates/boulder/src/cli/profile.rs
crates/boulder/src/root.rs
crates/moss/src/client/mod.rs
crates/moss/src/repository/manager.rs

When user adds repos manually via config and not via moss or boulder CLI, the repo will be uninitialized and dependent commands will fail.
This ensures all configured repos are initialized when running moss client

Ensure all repos are initialized

---

crates/boulder/data/profile.d/default-x86_64.yaml
crates/boulder/src/cli/build.rs
crates/boulder/src/cli/profile.rs
crates/boulder/src/profile.rs
crates/config/src/lib.rs
crates/moss/src/repository/mod.rs

Support merging system config files w/ user config files and add default profile to data dir that packagers can ship boulder with and use as default profile when invoking applicable boulder commands

Default boulder profiles

---

crates/moss/src/cli/mod.rs

This should fix issue #111 where the cli panics with supplied with --directory but no subcommand.  If no subcommand is specified, moss now defaults to printing help rather than panics

print help when the only argument is --directory

---

crates/moss/src/cli/inspect.rs

I just randomly noticed that the shown hashes for the layout output are incorrect, for some files at least. Seems like leading zeroes for a hash aren't printed, so the length of the hash is < 32 chars.
Examples (only showing some affected lines):
```
$ target/debug/moss inspect test/bash-completion-2.11-1-1-x86_64.stone
Layout entries       :
- /usr/share/bash-completion/completions/_mock - [Regular] 643ff65bbfaea9eeb0501febff14e5c
- /usr/share/bash-completion/completions/_mount.linux - [Regular] 9e284063682c78bdef54eba751f7a8
- /usr/share/bash-completion/completions/_nmcli - [Regular] a6a4317c64df97d84be1f53e3d75007
- /usr/share/bash-completion/completions/apt-build - [Regular] 161f224b130cbf8b14ffaf36a23a5e5
- /usr/share/bash-completion/completions/cfrun - [Regular] …
```

Print leading zeroes for hashes

---

crates/boulder/src/profile.rs
crates/config/src/lib.rs
crates/fnmatch/src/lib.rs
crates/moss/src/client/mod.rs
crates/moss/src/client/postblit.rs
crates/moss/src/repository/manager.rs
crates/moss/src/repository/mod.rs
crates/triggers/src/lib.rs

A few small  things I noticed when reviewing triggers.
`Config::merge` doesn't make sense at the API level as it causes `unimplemented`. Default API should just always return an array of configs and merging can be handled by the consumer.

Triggers cleanup

---

crates/moss/src/installation.rs

Just a small patch adding in a CACHEDIR.TAG into `.moss/cache` to prevent modern backup tools from backing up data in that directory.

moss: Add a CACHEDIR.TAG to `.moss/cache`

---

crates/moss/src/cli/remove.rs
crates/moss/src/cli/sync.rs
crates/moss/src/registry/transaction.rs

And allow sync to run if no upgrades exist, but removals do.
This doesn't change the behavior of sync, as it previously removed orphans. We just didn't present that information to the user nor allow it to run if only removals exists & not upgrades

List orphan removal from sync

---

boulder/data/macros/actions/cmake.yml
boulder/data/macros/actions/meson.yml
boulder/data/macros/arch/aarch64.yml
boulder/data/macros/arch/base.yml
boulder/data/macros/arch/emul32/x86_64.yml
boulder/data/macros/arch/x86.yml
boulder/data/macros/arch/x86_64-stage1.yml
boulder/data/macros/arch/x86_64-v3x.yml
boulder/data/macros/arch/x86_64.yml
boulder/data/recipeTemplate.yml

Note that a new x86_64-v3x.yml target definition was added in preparation for the point where we will begin building the scaffolding to use it.

boulder: Bring data/ up to parity with boulder-d

---

boulder/src/package/analysis.rs

This moves the Analysis output closer to the look of the other "work" stages, whilst still ensuring that ignored files get suitably highlighted to the eye of the packager in both shape, contrast and with a highlighted (yellow) explanation.

boulder: Tweak Analysis Phase output to look slick

---

boulder/src/build.rs
boulder/src/build/job/phase.rs
boulder/src/build/upstream.rs
boulder/src/main.rs
boulder/src/package/analysis.rs
boulder/src/package/emit.rs
crates/tui/src/lib.rs
crates/tui/src/styled.rs
moss/src/cli/index.rs
moss/src/cli/info.rs
moss/src/cli/list.rs
moss/src/cli/remove.rs
moss/src/cli/state.rs
moss/src/client/mod.rs
moss/src/main.rs
moss/src/package/render.rs
moss/src/state.rs

Resolves https://github.com/serpent-os/moss/issues/122
Before & After:

Disable styling on no-tty

---

Cargo.lock
Cargo.toml
moss/Cargo.toml
moss/src/cli/info.rs
moss/src/cli/list.rs
moss/src/cli/remove.rs
moss/src/cli/sync.rs
moss/src/client/install.rs
moss/src/package/mod.rs
moss/src/registry/mod.rs
moss/src/registry/plugin/active.rs
moss/src/registry/plugin/cobble.rs
moss/src/registry/plugin/repository.rs
moss/src/registry/transaction.rs

This PR replaces the bitflags functionality with an in-house implementation.
I think we all agree on reducing the number of dependencies where it makes sense, and I also think bitflags is one dependency worth removing. It is based on a `macro_rule` which is able to escape the original Rust syntax (think of that `: u8` syntax to specify that flags are bytes. That's a C++ notation!), making code a little confusing. `macro_rules` have too much freedom of toying with the code, IMO.
The new `Flags` struct is a type-safe and value-safe collection of flags. It is not possible to build an invalid collection of Flags. The idea is based on `std::fs::OpenOptions`.
Did you note that `bits()` private method? That's a micro-optimization. While I could implement the `contains()` method using pure …

Drop the bitflags dependency

---

boulder/src/package/emit.rs
crates/tui/src/lib.rs
crates/tui/src/pretty.rs
moss/src/cli/extract.rs

This is mostly code style you may not agree with, but I think the replacement of the reader and writer wrappers is a win.
- `TermSize` now implements the Default trait, and the previous `get_size()` function is now `TermSize`'s constructor.
- `ProgressReader` and `ProgressWriter` are replaced by indicatif's `wrap_read()` and `wrap_write()`:
- Shorter code
- Prevents a previously possible division by zero
- Those wrapper expose more methods than `read()` and `write()` for convenience

crates/tui: Simple refactor

---

crates/vfs/src/lib.rs
crates/vfs/src/path.rs
crates/vfs/src/tree/builder.rs
crates/vfs/src/tree/mod.rs
moss/src/cli/info.rs
moss/src/client/mod.rs

We process a LOT of paths and the Path API is very costly. Let's do some slightly less robust logic on strings directly.
Is an 8% speedup from my test of blitting a root w/ `gdm` added.

Dont use Path API

---

boulder/data/macros/arch/base.yml

boulder/data/macros: Ensure gcc's lto is parallelized

---

boulder/src/package/emit/manifest/json.rs
crates/stone/src/payload/meta.rs

A couple more fixes to ensure `boulder-rs` -> legacy tooling compatibility

Moar manfiest compatibility 

---

boulder/src/cli/build.rs
boulder/src/cli/chroot.rs
boulder/src/cli/recipe.rs
boulder/src/recipe.rs

Due to our magical namespace swapping we seem to "forget" where we are, so store the full path to the CLI argument when building with relative paths such as `boulder build stone.yml`

boulder/cli/build: Form full absolute path for CLI arguments

---

crates/tui/src/pretty.rs
moss/src/cli/mod.rs
moss/src/cli/remove.rs
moss/src/cli/search.rs
moss/src/cli/sync.rs
moss/src/client/install.rs
moss/src/client/prune.rs
moss/src/db/meta/mod.rs
moss/src/package/meta.rs
moss/src/registry/mod.rs
moss/src/registry/plugin/active.rs
moss/src/registry/plugin/cobble.rs
moss/src/registry/plugin/mod.rs
moss/src/registry/plugin/repository.rs

First implementation step of #34.
Outputs:
```text
./target/debug/moss -D ~/Personal/SerpentOS/SOSROOT/ search gcc  -i
gcc       GNU C++ standard library and compiler 
```
```text
fforni@fedora:~/Personal/SerpentOS/moss$ ./target/debug/moss -D ~/Personal/SerpentOS/SOSROOT/ search gcc  
gcc-32bit-devel       Provides development files for gcc-32bit gcc-dbginfo                          Debugging symbols for gcc 
gcc-32bit            Provides 32-bit runtime libraries for gcc gcc                      GNU C++ standard library and compiler 
gcc-32bit-dbginfo              Debugging symbols for gcc-32bit gcc-devel                            Development files for gcc 
```
(Github destroyed the latter output. Inside a terminal it's well aligned). Also, package names are **bold**.
I'm not sure we …

moss: Allow to search for packages with one keyword

---

boulder/src/package.rs
boulder/src/package/emit.rs
boulder/src/package/emit/manifest.rs
boulder/src/package/emit/manifest/json.rs
justfile

This makes it easier to see when `boulder build -bN` has been used to build a set of artefacts.
Example:
```diff
diff --git a/x/xorriso/manifest.x86_64.jsonc b/x/xorriso/manifest.x86_64.jsonc
index e535ffc3..baef6688 100644
--- a/x/xorriso/manifest.x86_64.jsonc
+++ b/x/xorriso/manifest.x86_64.jsonc
@@ -38,5 +38,6 @@
},
"source-name": "xorriso",
"source-release": "1",
-       "source-version": "1.5.6.pl02"
+       "source-version": "1.5.6.pl02",
+       "build-release": 2
}
```

boulder: include buildrel in jsonc manifest

---

boulder/src/recipe.rs

As mentioned in the packaging channel, we should always run the x86 build before the x64 one so that the x64 install phase clobbers the x86 one and not vice-versa.

boulder: Always run x86 build before x64 one

---

boulder/src/package/analysis/handler/elf.rs

This wasn't correct and prevented the glibc build from having a provides on the interpreters.

boulder: Fix interpreter detection

---

crates/stone/src/read/mod.rs
crates/vfs/src/tree/builder.rs
moss/build.rs
moss/src/client/mod.rs

All files under `src` are already rerun-if-changed by default, so those lines can be removed.
The new directives ensure that the moss build script is always recompiled if boulder or cargo lock changes. This should ensure that the boulder binary always has the latest commit SHA even if the underlying moss library did not change.

Ensure git hash is up-to-date for boulder

---

.cargo/config.toml
.github/workflows/ci.yaml
.github/workflows/nightly.yaml

Flags:
- Use lld even on distros that do not use lld for the system linker (like Solus) to speed up builds, especially incremental ones
- Compress debug symbols with zstd for significant space savings
- Enable the new system mangler format for improved ABI reports

repo: Add default rust flags

---

Cargo.lock
Cargo.toml
crates/vfs/Cargo.toml

- Update all dependencies, except for nix which requires code changes
- Enable some more features of use to us in the reqwest library, namely http2 support and support for all supported content encodings.

deps: Update

---

Cargo.lock
Cargo.toml
moss/Cargo.toml
moss/src/request.rs

once_cell functionality was integrated into the stdlib in Rust 1.70.0. Switch to it so we can drop once_cell as a dependency.
While OnceLock is functionally similar to the thread-safe modules in once_cell the APIs are somewhat different. In this case the biggest difference is that you can't declare the function that creates the object when you declare the object itself, any caller that wants to use the object needs to provide the function to create it if it does not already exist. This is trivially worked around by wrapping the object in a function, which is what I did here.

all: Use stdlib OnceLock for HTTP client

---

boulder/src/architecture.rs
boulder/src/build/job/phase.rs
boulder/src/build/pgo.rs
boulder/src/build/root.rs
boulder/src/cli/profile.rs
boulder/src/draft/build.rs
boulder/src/macros.rs
boulder/src/package.rs
boulder/src/package/analysis.rs
boulder/src/profile.rs
crates/fnmatch/src/lib.rs
crates/stone_recipe/src/lib.rs
crates/stone_recipe/src/script.rs
crates/stone_recipe/src/tuning.rs
crates/vfs/src/tree/builder.rs
crates/vfs/src/tree/mod.rs
moss/src/cli/remove.rs
moss/src/client/cache.rs
moss/src/client/prune.rs
moss/src/client/verify.rs
moss/src/db/layout/mod.rs
moss/src/db/meta/mod.rs
moss/src/package/meta.rs
moss/src/registry/mod.rs
moss/src/registry/plugin/cobble.rs
moss/src/repository/manager.rs
moss/src/repository/mod.rs

While testing ccache I noticed that cache hit rate was extremely low. After some debugging I noticed that the CFLAGS and other environmental variables and macro scripts were not being set deterministically. This is problematic for ccache as it hashes the compiler arguments as part of the key and the order matters to get the same key on a future run.
The cause of this non-determinism is the Rust stdlib HashMap and HashSet, for which the default hasher used a random seed. To solve this switch to BTreeMap and BTreeSet from the stdlib. Since non-determinism is just generally a bad idea for build tools and package management software replace ALL uses of HashMap and HashSet repo-wide.
Tested by building a package with ccache enabled and using `ccache --show-stats` in the package recipe to …

all: Switch to deterministic BTreeMap/BTreeSet

---

boulder/data/macros/arch/base.yml
boulder/src/build/job/phase.rs
crates/stone_recipe/src/tuning.rs
test/base.yml

From the Rust docs:
> A space-separated list of custom flags to pass to all compiler invocations that Cargo performs. In contrast with `cargo rustc`, this is useful for passing a flag to _all_ compiler instances. (...) This string is split by whitespace
And define the default for that flag to be `-Cforce-frame-pointers`, which from the Rust docs force enables frame pointers. Note that setting this flag to `=false` or leaving it off does not necessarily mean that frame pointers will be removed as they can still be enabled by other means.
Though it is unlikely to be needed setting `frame-pointer: false` in the tuning section of a recipe will remove this flag.

boulder: Add RUSTFLAGS, enable frame pointers by default

---

boulder/data/macros/arch/base.yaml
boulder/src/build/job/phase.rs
boulder/src/recipe.rs

Wire up SOURCE_DATE_EPOCH. This environmental variable will always be set in the buildroot and will be set according to the following priority:
- Check to see if the environmental variable is already set, if so propagate it
- Check the return value of `git log -1 --format="%at"`, which returns the timestamp of the last commit of the git repo
- Use the current time

boulder: Add SOURCE_DATE_EPOCH

---

boulder/data/macros/actions/cargo.yaml

This allows multiple arguments to the `%cargo_install` macro, in case there are several binaries to install
See also https://github.com/getsolus/ypkg/pull/90

Allow multiple arguments to %cargo_install

---

boulder/Cargo.toml
boulder/src/package/analysis/handler/elf.rs

The Rust elf library returns `EM_386` for x86 ELF objects, while we used `x86` as the ISA with the dlang boulder. This results in emul32 packages that are not compatible with packages already in the volatile repo.
To "Fix" this make sure we use `x86` for all dependencies, while also adding each dependency twice as both `x86` and `386`. This ensures that newly built packages are compatible with existing ones while also allowing us to switch fully to `386` once every existing emul32 package has been rebuilt. We can also just drop the duplicate `386` provide if we decide to use `x86` instead without any repo issues.

boulder: Fix emul32 incompatibility with dlang boulder

---

boulder/src/env.rs

We don't want to default to using the system moss root for boulder, as we want paranoid levels of protection of the system root (boulder shouldn't be able to
accidentally clobber it due to a bug).
Use a shared moss root in the boulder cache directory instead.
Resolves #271

boulder: Use shared moss root in boulder cache

---

boulder/data/macros/actions/meson.yaml

meson uses pkgconf and cmake to find dependencies

boulder: Add cmake and pkgconf dependencies to meson setup macro

---

boulder/data/macros/actions/cargo.yaml
boulder/data/macros/arch/base.yaml

Let us control rust optimization options via our flags.
Also fixes the buggy cargo_build macro not passing intended --release optimization options.

Boulder: hook up rust optimization flags & adjust cargo_build macro

---

crates/serpent_buildinfo/build.rs

This suppresses the cfg clippy warnings that were added in Rust 1.80. These are false positives as clippy is not aware that these are set by build.rs.

clippy: Suppress CFG warning

---

crates/container/src/lib.rs

I'm getting this weird error when running moss from a chroot:
```
Error: sync: client: postblit: container: exited with failure: EINVAL: Invalid argument
```
This change helped me narrow down what's going wrong (it's the call to `pivotroot`).

Split ContainerError::Nix into more specific variants

---

boulder/data/macros/arch/base.yaml
boulder/src/build/job/phase.rs
boulder/src/build/root.rs
boulder/src/container.rs
boulder/src/paths.rs

Similarly to ccache, sccache can be used to cache rust compiler artefacts. Support is enabled via the same --compiler-cache flag.
Resolves #290.
**Testing**
`starship`:
sccache enabled (1st run)   : 4m27.21s  
sccache enabled (2nd run) : 2m38.11s
sccache disabled                  : 3m14.12s
`~/.cache/boulder/sccache/` is populated after building `starship`

boulder: Add support for sccache

---

crates/container/src/lib.rs

This was meant to mirror the name of the function being called, I just noticed it didn't because of the missing underscore.

Update Display string for ContainerError::PivotRoot

---

boulder/src/build/root.rs

Updates the GNU toolchain packages after serpent-os/recipes#207

boulder: Update GNU toolchain packages

---

boulder/src/build/upstream.rs
boulder/src/draft/upstream.rs
boulder/src/package/analysis.rs
boulder/src/package/emit.rs
moss/src/cli/index.rs
moss/src/client/mod.rs
moss/src/client/verify.rs
moss/src/repository/manager.rs

Fixed #313 
```
moss on  fix/indicatif-output [$!?] is 📦 v0.1.0 via 🦀 v1.80.1
❯ cargo run -- -D .root it mesa -y &>moss.log
moss on  fix/indicatif-output [$!?] is 📦 v0.1.0 via 🦀 v1.80.1 took 4s
❯ cat moss.log
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/moss -D .root it mesa -y`
The following package(s) will be installed:
brotli             1.1.0-4   json-c              0.17-2   libgpg-error        1.46-1   libxml2           2.12.4-6   p11-kit-libs      0.25.3-2   util-linux        2.40.2-8
bzip2              1.0.8-2   kbd                2.6.4-6   libpciaccess        0.17-2   libxshmfence       1.3.2-1   perl              5.38.2-7   wayland           1.23.0-4
ca-certificates  20240708-2   kmod                  31-8   libseccomp …
```

tui: Suspend indicatif & print normally

---

moss/src/client/mod.rs
moss/src/client/verify.rs
moss/src/lib.rs
moss/src/signal.rs

moss: Ignore SIGINT during blit

---

moss/src/request.rs

Fixes #332. Seems to not have negative consequences elsewhere.

moss: Disable automatic referer header in reqwest::ClientBuilder

---

crates/vfs/src/tree/builder.rs
crates/vfs/src/tree/mod.rs
moss/src/cli/info.rs
moss/src/client/mod.rs

Basically fix `path() path() path() path() path()` being called 100x times. Cache it on first invocation by wrapping `BlitFitle` and calling these expensive methods only once.
Wall time went from 14.4s -> 600ms xD

moss: vfs: Cache expensive path calc / allocations

---

Cargo.lock
Cargo.toml
boulder/Cargo.toml
boulder/src/package/analysis.rs
boulder/src/package/analysis/handler.rs
moss/src/dependency.rs

Uses mailparse to parse the RFC style package information from .dist-info or .egg-info directories and provides a python provider from the name.
Based off `pip3 show`

boulder: Hook up python providers

---

crates/container/src/lib.rs

This fixes an issue where the sccache daemon could not start with networking disabled. Issue was not noticed as most rust projects do not vendor their dependencies.

crates/container: Ensure localhost networking is setup

---

moss/src/db/meta/mod.rs

This fixes the following error:
```
Error: build: build recipe: root: moss client: repository manager: meta db: diesel: UNIQUE constraint failed: meta_licenses.package, meta_licenses.license
```
It appears that the section that generates metadata for inserting into the database is generating multiple entries with the same id and value (these tables all have primary keys on the id and values). Perhaps the better solution is to de-duplicate the array before inserting it or figure out why it's creating duplicate items in the first place, but this gets things building on my machine at least.

moss: Fix duplicate inserts

---

boulder/data/macros/actions/cargo.yaml
boulder/data/macros/arch/base.yaml

Instead of building packages in debug profile (which requires workarounds for at least every package that uses rust-embed) build in release profile but with environmental variable overrides for the settings we need in order for RUSTFLAGS to take precedence.
This was tested by building several packages with different LTO profiles and verifying that they built as expected.
Also, add a few helper definitions for the artifact directory and the cargo options so that they can be used in other places.

boulder: Update cargo macros

---

moss/src/client/mod.rs
moss/src/client/prune.rs
moss/src/db/layout/mod.rs
moss/src/db/meta/mod.rs
moss/src/db/mod.rs
moss/src/db/state/mod.rs
moss/src/environment.rs
moss/src/repository/manager.rs

We should have been using transactions for all mutable queries. We can always use `exclusive` since we're behind mutex

Use sqlite exlusive transactions & optimize batching

---

boulder/Cargo.toml

emul32 libs will now depend on 386 variants of the provided emul32 libs instead of x86.
Part of #223.

boulder: cfg! compat_dlang_emul_both -> compat_dlang_emul_flush

---

boulder/data/macros/actions/python.yaml

The packaging module is used to determine python dependencies automatically.

boulder/data: Add python-packaging as a dep for setup.py

---

boulder/src/cli.rs
boulder/src/env.rs

For distro packages this will continue the /usr/share/boulder path for rootless boulder operation; however, for home-grown builds use XDG_DATA_HOME/boulder if the path exists and is non-empty.

boulder: Use XDG_DATA_HOME/boulder for data directory when appropriate

---

boulder/src/build/job/phase.rs

Resolves https://github.com/serpent-os/recipes/issues/99

boulder: set CPP env to clang-cpp for llvm toolchain

---

Cargo.lock
Cargo.toml
boulder/Cargo.toml
boulder/src/cli/build.rs

By default set the priority to SCHED_BATCH to hint to the scheduler that boulder is not interactive and to optimize scheduling for throughput. This should help improve system responsiveness during high CPU builds.
In case the user doesn't want this for some reason also add a flag to disable this behavior.

boulder: Set SCHED_BATCH for builds

---

boulder/src/package/analysis/handler.rs
boulder/src/package/analysis/scripts/get-py-deps.py

Compiles get-py-deps.py into the binary then executes at runtime using `python3 -c`
get-py-deps.py uses `importlib.metadata` from the python std to get a list of dependencies from either .egg-info or .dist-info paths. Then uses APIs from packaging to sanitize those dependencies.
By default "extra" dependencies are ignored and it is up to the packager's discrection to optionally include them.
Dependencies that depend on environmental markers e.g. Windows, python3 > $version will be correctly evaluated and included if necessary.
Depends on https://github.com/serpent-os/recipes/pull/359

boulder: Add support for automatic python dependencies

---

Cargo.lock
Cargo.toml
boulder/src/cli/build.rs
moss/Cargo.toml
moss/src/client/mod.rs
moss/src/client/verify.rs
moss/src/signal.rs

https://www.freedesktop.org/wiki/Software/systemd/inhibit/
moss: prevents the system from going down during critical operations.
boulder: Allows the packager to keep suspend options enabled without the system going down during a long running build.

moss+boulder: Inhibit system from going down during crucial operations

---

boulder/data/macros/actions/pgo.yaml
boulder/data/macros/arch/base.yaml

split-machine-functions is an optional flag for PGO optimize builds that uses the profile data to split hot/cold/unlikely .text sections.
Although disabled by default, BOLT does it's own version of splitting hot/cold .text which split-machine-functions gets in the way of.

boulder/data: Ensure split-machine-functions are disabled in bolt flags

---

boulder/src/cli/build.rs
crates/container/src/lib.rs

Fixes needed to run boulder inside docker:
- systemd is probably not pid 1 and we can't rely on inhibit working (don't make this a fatal error)
- We have some logic around term fg capturing to recapture ctrl-c functionality after invoking bash within user namespace. This fails when we don't have a controlling terminal. This can be ignored in those cases and shouldn't be fatal.

Run boulder inside docker fixes

---

boulder/data/macros/actions/misc.yaml

Most icon themes benefit from having their icon cache pre-generated at build time.
The invocation for doing so follows a distinct pattern, hence this macro could perhaps be gainfully used as a simpler substitution.

boulder: Add `%gtk_update_icon_cache` action macro

---

crates/container/src/lib.rs

Accidently killed in 8fa3d1fb5427c4376bcb8f78a31e5d908ca5d1ee

crates/container: Add back umask after pivot_root

---

boulder/src/draft/build/python.rs

python_build macro dannae exist

boulder/draft: Fix a typo python_build -> python_setup

---

boulder/src/package/analysis/handler.rs

https://peps.python.org/pep-0503/#normalized-names
pip and python packaging APIs use case-insensitive names, until now this hasn't been a problem until we started providing the python "Jinja2" whilst dependencies were looking for "jinja2".
Apon landing in summit we need safety rebuilds of all python packages with this change.

boulder: Normalize all python providers to lowercase

---

boulder/src/draft/metadata.rs

We need to match against "special" providers first before falling back to the default simple case, as it'll break the match on first matcher.

boulder/draft: Fix github matching

---

boulder/src/draft.rs

This will most likely be the closest match, plus we write out the recipe file unconditionally then much to deangst to our packagers.

boulder/draft: Default to autotools on unhandled build system

---

Cargo.lock
Cargo.toml
boulder/Cargo.toml
boulder/src/cli/recipe.rs
boulder/src/draft.rs
boulder/src/draft/monitoring.rs

Attempt to match the id from release-monitoring and any CPE from cpe-guesser.

boulder: Write a monitoring.yaml file with boulder new

---

boulder/src/package/collect.rs

Boulder had a needless check for `starts_with` which was causing erroneous package splitting in several cases. For instance, consider the following simplified patterns:
```
- llvm-libs:
paths:
- /usr/lib/libLLVM.so.*
- llvm-devel:
paths:
- /usr/lib/libLLVM.so
```
With this setup the file `/usr/lib/libLLVM.so.18.1` should be patterned into `llvm-libs`, however since the `starts_with` match was checked first it would end up in `llvm-devel`. The point of this was to ensure that we could have "globs" that matched directories that matched subfiles/subdirectories and in order to preserve that behavior we instead match twice, once on the submitted pattern and again with `/**` appended to get a recursive glob.
Also while we're at it apply a minor adjustment to escape the directory so that all …

boulder: Fix pattern matching

---

boulder/data/macros/actions/cargo.yaml
boulder/data/macros/actions/cmake.yaml
boulder/data/macros/actions/meson.yaml
boulder/data/macros/actions/misc.yaml
boulder/data/macros/actions/perl.yaml
boulder/data/macros/actions/pgo.yaml
boulder/data/macros/actions/python.yaml
boulder/data/macros/arch/base.yaml
boulder/src/build/job/phase.rs
boulder/src/build/root.rs
crates/stone_recipe/src/lib.rs

Note: I bundled these together because most of them are pretty small and I worked on all of them at the same time, but I can split them out if needed (they're separate commits per-change).
Changes:
- Add build-id flags and enable it by default
- Default to compressing debug symbols with zstd. This reduces on-disk space of debug symbols significantly at the cost of higher package sizes.
- Define `-flto=%(jobs)` for GCC as "thin" LTO since it behaves roughly similar to the LLVM equivalent. Add `-flto=%(jobs) -flto-partition=one` as a new "full" variant of LTO for GCC.
- Add `-ffat-lto-objects` flags and enable them by default. These are needed if building static archives with LTO that are used by the alternate toolchain (IE if the static archives are built with GCC then fat-lto-objects is …

boulder: Numerous toolchain changes

---

boulder/src/draft/monitoring.rs

Just return an empty formatted output

boulder/draft: Don't match monitoring on metadata name extract failure

---

boulder/data/macros/actions/qt-kde.yaml
boulder/data/macros/arch/base.yaml

This adds some patterns and macros that are designed to provide the default options for KF6/Qt6 based builds.

boulder/macros: Add kf6 macros

---

boulder/src/draft/metadata/basic.rs

A filename such as `drm_info-v2.7.0.tar.gz` will now match properly.
Part of #414.

boulder/draft/metadata: Match underscores in basic first capture group

---

Cargo.lock
Cargo.toml
boulder/Cargo.toml
boulder/src/draft/upstream.rs

Using infer will help us catch specalized extension types
e.g.
`.whl` is a `.zip`
`.gem` is a `.tar`

boulder/draft: Use infer to get extension type to perform extraction

---

Cargo.lock
boulder/src/draft/build.rs
boulder/src/draft/build/ruby.rs

Split ruby support into:
- Ruby .gem files which only need a `%gem_install` and contain a layout
containing several tarballs
- Normal tarballs containing a .gemspec file, which'll need a `%gem_build`
and `%gem_install` macros

boulder/draft: Add initial ruby support to boulder new

---

boulder/src/build/root.rs

Merge after AerynOS/recipes#683

boulder: Adapt GNU toolchain to libstdc++ split

---

boulder/data/macros/arch/base.yaml

Now that Polly is no longer linked into libLLVM/clang directly we need to load it as a plugin explicitly in order for it to be used.
Don't ask how long this took me to figure out.
Merge after AerynOS/recipes#762

boulder/macros: Update polly flags

---

README.md
justfile

Not everything has been moved over yet so there are still some Serpent references.

README: Update a few references to Aeryn OS where applicable

---

Cargo.lock
Cargo.toml

Not all of them though. Can upgrade more in follow-up PRs. This is to get the repo into a state where we can have as few duplicate dependencies in `infra` as reasonable without much work :)

Upgrade some dependencies

---

boulder/data/macros/actions/cmake.yaml
boulder/data/macros/actions/meson.yaml
boulder/data/macros/actions/ninja.yaml
boulder/data/macros/actions/qt-kde.yaml

Cmake:
- Re-introduce support for using make as the build server
- Switch to invoking the build server via cmake directly
- Update ctest options
- Fix handling of build flags
- Build flags are now imported from environment directly
- `-DNDEBUG` is now correctly added to build flags when using `Release` profile
- Enable verbose makefiles and disable stripping by default
Ninja:
- Add ninja-specific macros for building, installing, and testing
Meson:
- Remove unnecessary exports of build flags
- Update build options

boulder/macros: Update cmake/ninja/meson macros

---

Cargo.lock
Cargo.toml

I asked the author of `indextree` for a new release, and within less than a day he released it!
This leaves only dialoguer depending on thiserror 1.x, everything else is on 2.x; another duplicate dependency soon to be removed :)

Upgrade itertools, indextree, strum

---

boulder/data/macros/arch/aarch64.yaml
boulder/data/macros/arch/riscv64.yaml
boulder/src/architecture.rs

RISC-V:
LLVM: Doesn't yet support generic-ooo
AARCH64:
GCC: While passing -m64 in clang is fine, its not for gcc

Arch: aarch fixes and add riscv64 definition

---

moss/src/client/mod.rs

As children of dirs are pre-structured by vfs, we can blit them all in parallel safely.

moss/client: Blit entries in parallel

---

boulder/data/macros/arch/base.yaml

This was causing build failures due to causing compiler failures with `-Werror`

boulder: Remove assembler directive

---

boulder/data/macros/arch/base.yaml
boulder/src/build/job/phase.rs
crates/stone_recipe/src/tuning.rs

This adds FFLAGS to the boulder build env. I tested the various flags supported by gfortran and flang and added them where appropriate.

boulder: Add Fortran support

---

boulder/data/macros/actions/autotools.yaml
boulder/data/macros/arch/base.yaml
boulder/data/profile.d/default-x86_64.yaml
boulder/src/build.rs
boulder/src/build/root.rs
moss/src/client/boot.rs

With this change, the build scripts generated by boulder from the stone.yaml recipes are no longer affected by the /usr/bin/sh symlink, which means that we can now safely point that to dash for a potential increase of up to +20% faster configure runs for e.g. gettext.
This commit also creates dedicated *_with_bash fallback autotools actions which should ensure that stubborn packages whose build systems rely on the presence of a bash shell can now simply use the *_with_bash actions.
In addition, add helix, less and ripgrep to roots for a nicer chroot experience when troubleshooting or writing/testing patches inside the chroot (yes, this is a really nice workflow actually).
TODO: The extra chroot packages really ought to be user-controlled (with a decent, if minimal fallback) as a boulder …

boulder: use /usr/bin/bash for script shebangs

---

boulder/src/package/analysis/handler.rs

Boulder generates providers by using the module's name. If module's name contains a '_', it will cause a provider/dependency mismatch. This is solved by simply adding additional providers by replacing '_' with '-' in the module's name.
I tested it by rebuilding python-typing_extensions and it got resolved, even if the module is looking for python(typing-extensions(3.11)), which got generated by boulder too.

boulder: Normalize python providers

---

Cargo.toml
boulder/src/package/emit.rs
crates/container/src/lib.rs
moss/src/cli/extract.rs
moss/src/client/cache.rs
moss/src/installation/lockfile.rs
moss/src/signal.rs

I have not tested this (nor am I certain how to best do that). Much more straight-forward than my failed rustix PRs though.
I'm happy with rebasing this over time if keeping up with the ecosystem is not currently a priority. (I just like doing this sort of work and had fs-err `File::options` on my todo > got that merged today > I checked out where it would be useful > found `OpenOptions` usage in this repo > found more dependencies that were not at the latest version > found an unnecessarily large unsafe block while upgrading nix)

Dependency upgrades and other maintenance

---

boulder/data/macros/arch/base.yaml

This needs to be removed once we are done rebuilding, so it can act as a signal that we need to redo recipes that use it.

boulder: Add %(completionsdir) for rebuild compat

---

boulder/data/macros/actions/qt-kde.yaml

Because we're constructing the cmake command manually (as opposed to say adding specific qt cmake options) we need to manually add binary(ninja) to the cmake deps.

boulder: Fix Qt/KDE macros

---

Cargo.toml

Reduces boulder debug binary size from over 260M to about 120M, and moss debug binary size from almost 230M to about 105M.

Reduce debug info for dev profile

---

Cargo.toml
boulder/src/paths.rs
boulder/src/profile.rs
moss/src/package/meta.rs
moss/src/package/mod.rs
moss/src/repository/mod.rs
moss/src/state.rs

Debug printing one of these previously would have produced `Id("the-actual-id")`, now just `"the-actual-id"`.

Remove "Id()" from Debug impls

---

.github/workflows/release.yaml

… and rename it accordingly because it's no longer for nightlies.

ci: Update "nightly" release workflow to run on tag push

---

crates/stone/src/read/mod.rs
moss/src/cli/inspect.rs

Adds a `--check` option to the `moss inspect` command to verify the integrity of .stone files.
- Added `--check` flag to enable integrity checking mode
- Added `--quiet` flag for suppressed output
- Implemented `check_stone_integrity()` helper function
- Exit 0 if all files pass integrity checks
- Exit 1 if any file fails validation
- Added test coverage for valid, corrupted, and malformed stone files
```bash
moss inspect --check some.stone
moss inspect --check --quiet file1.stone file2.stone
```
Closes #517

moss: Add --check option to moss inspect command

---

boulder/data/macros/actions/misc.yaml

Autodiscovers installed docbook catalogs for local use in builds that
require docbook to build documentation.
The action is intended to be used like so:
```yaml
(...)
builddeps  :
- (...)
- docbook
- docbook-xsl
- docbook-(...)
- (...)
environment: |
%export_docbook_catalogs
(...)
```
**Test Plan**:
- build new boulder with `just get-started`
- use that boulder to build gtk-3 with:
```
environment: |
%export_docbook_catalogs
```
- observe the following output:
```
│S│ The work directory %(workdir) is /mason/build/x86_64/gtk-3.24.50.tar.xz
│S│ ++ find /usr/share/defaults/docbook -type f -name catalog -exec echo -e 'file://{} ' ';'
│S│ + export 'XML_CATALOG_FILES="file:///usr/share/defaults/docbook/docbook-dtd/catalog 
│S│ file:///usr/share/defaults/docbook/docbook-xsl/catalog "'
│S│ + …
```

boulder: Add %export_docbook_catalogs misc action

---

boulder/src/cli/build.rs
crates/tools_buildinfo/src/lib.rs

- Display boulder version at start of build
- Show package name, version, source release, and build release being built
- Correct `get_full_version()` documentation to match actual output format
before:
```bash
The following package(s) will be installed:
...
```
after:
```bash
boulder v0.25.6 (Git ref b2558d8445fd8ca3eff90165981adaa7730a3921-dirty)
└─ building llvm-16.0.4-8-1
The following package(s) will be installed:
...
```
Closes #460

boulder: Improve build header

---

boulder/src/draft/monitoring.rs

Closes #511 
- For requests to release-monitoring.org and cpe-guesser.cve-search.org, HTTP errors and connection failures now show warnings and continue with empty response instead of crashing
- Informative comments included in the `monitoring.yaml` based on failure type for CPE failures:
- Service errors: `# CPE service returned error, retry later <date>`
- Connection failed: `# CPE service unreachable, retry later <date>`
- No results: `# No CPE found, last checked <date>`
I've tested this by blocking access to the sites and running boulder new on the abseil-cpp project:
```bash
boulder new https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz
```
With release-monitoring.org inaccessible:
```bash
■ Extracting …
```

boulder: improve boulder new error handling for `boulder new`

---

boulder/src/package/analysis/handler/python.rs

I just finished rebuilding all of the python packages that have versioned dependencies, now it's time to drop versioned providers.
Part of https://github.com/AerynOS/os-tools/issues/496

boulder: Drop versioned python deps

---

Cargo.lock
Cargo.toml
boulder/Cargo.toml
boulder/src/build.rs
boulder/src/build/git.rs
boulder/src/build/upstream.rs

Per discussion on matrix, this refactors git upstream hash resolution to use `git rev-parse` on cloned repositories instead of `git ls-remote` during build initialization.
This is a backwards compatible change but should allow for more flexibility in the `ref` specified in the `stone.yaml`. In particular any ref or hash that `git rev-parse` can parse should resolve to the full 40 character hash.
I've include a suite of tests for both the new `resolve_git_ref` and `update_git_upstream_refs` that test various refs and hashes in different formats. I think it is comprehensive enough, but let me know if you see any obvious holes.

Boulder: Refactor boulder git hash resolution

---

boulder/src/package/collect.rs

fs::read_dir() is not deterministic
Should resolve #564.

boulder: Sort layout entries by name before processing

---

boulder/data/macros/actions/qt-kde.yaml

Qt6 doesn't actually ever read these files if present, so the only thing this was doing was inflating package sizes. I didn't exhaustively check the Qt5 one like I did the Qt6 code but given that we're not actually using the Qt5 one I think we can just drop it too.

boulder: Remove qmlcachegen macros

---

boulder/src/package/analysis/handler.rs
crates/stone_recipe/src/lib.rs

Some packages need libtool files to function correctly

boulder: Allow packager to keep .la files

---

Cargo.lock
Cargo.toml
crates/config/Cargo.toml
crates/config/src/lib.rs
crates/fnmatch/Cargo.toml
crates/fnmatch/src/lib.rs

Like for disks-rs, there's a bunch of windows-specific stuff being added to the lockfile (because you can't declare your crate only works on some targets, all target-specific dependencies of your dependencies get recorded in the lockfile). This should not be a meaningful regression to build time, and could very well be an improvement (I haven't benchmarked).

Some dependency updates

---

boulder/data/macros/actions/misc.yaml

The previous flags didn't _quite_ do what I wanted, so switch `--batch` back to `--force` so that patch won't attempt to reverse patches that have already been flagged. The `--forward` flag does the same thing and is technically redundant with `--force` but it makes it clear what patch should be doing.

boulder: Adjust patch again

---

boulder/data/macros/arch/base.yaml

Unfortunately it is error prone to watch configure/cmake/meson logs to see which packages need `-Wl,--undefined-version` since if the flag doesn't work they'll just end up skipping using it. Since we do want version scripts to be applied if present let's just add the appropriate flag to allow for version scripts with undefined or duplicate symbols.

boulder: Add undefined-version ldflag

---

moss/src/cli/sync.rs
moss/src/client/install.rs

Add tracing to the `moss sync` command per #558 following the same pattern established in the `install` command #563.

moss: Add tracing to sync command
